config/routes.rb
Rails.application.routes.draw do

  root :to => "pacients#index"
  devise_for :users
  resources :pacients

end

app/models/pacient.rb
require 'carrierwave/orm/activerecord'

class Pacient < ActiveRecord::Base
  validates :name, presence: true
  validates :birth, presence: true
  validates :dependents, presence: true, inclusion: {in: (0..50)}
  validates :cpf, uniqueness: true
  validate :validate_cpf

  belongs_to :user

  mount_uploader :picture, ::PictureUploader

  def validate_cpf
    if cpf
      lista_cpf = cpf.gsub('.' ,'').gsub('-', '').split('')
      if lista_cpf.length == 11
        soma = 0
        mult = 10

        for i in (0..lista_cpf.length - 3)
          soma += lista_cpf[i].to_i * mult
          mult -= 1
        end

        mod = soma % 11

        if mod == 0 or mod == 1
          validator1 = 0
        else
          validator1 = 11 - mod
        end

        soma = 0
        mult = 11

        for i in (0..lista_cpf.length - 2)
          soma += lista_cpf[i].to_i * mult
          mult -= 1
        end

        mod = soma % 11

        if mod == 0 or mod == 1
          validator2 = 0
        else
          validator2 = 11 - mod
        end

        unless cpf[-2].to_i == validator1 and cpf[-1].to_i == validator2
          errors.add(:cpf, "Cpf inválido!")
        end

      else
        errors.add(:cpf, "Cpf de comprimento inválido!")
      end

    else
      errors.add(:cpf, "Can't be blank")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_many :pacients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pacients_controller.rb
class PacientsController < ApplicationController

  def index
    @pacients = Pacient.all
  end

  def new
    @pacient = current_user.pacients.build
  end

  def show
    @pacient = current_user.pacients.find(params[:id])
  end

  def edit
    @pacient = current_user.pacients.find(params[:id])
  end

  def create
    @pacient = current_user.pacients.build(pacient_params)
    if @pacient.save
      redirect_to root_path, notice: "Paciente criado com sucesso."
    else
      render :new
    end
  end

  def update
    @pacient = current_user.pacients.find(params[:id])
    if @pacient.update_attributes(pacient_params)
      redirect_to root_path, notice: "Paciente atualizado com sucesso."
    else
      render :edit
    end
  end

  def destroy
    @pacient = current_user.pacients.find(params[:id])
    @pacient.destroy

    redirect_to root_path, notice: "Paciente excluido com sucesso."
  end

  private

  def pacient_params
    params.require(:pacient).permit(:name, :birth, :dependents, :cpf, :picture)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pacients_helper.rb
module PacientsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Cadastre
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

body
  nav class="navbar navbar-inverse navbar-fixed-top"
    .container-fluid
      .navbar-header
        =link_to(image_tag("cadastre.png", height: 50), root_path)
      

      #navbar.navbar-collapse.collapse
        ul class= "nav navbar-nav navbar-right"
          li = link_to("Inicio", root_path)
          li = link_to(current_user.email, root_path)
          li = link_to("Cadastrar paciente", new_pacient_path)
          li = link_to('Sair', destroy_user_session_path, :method=>'delete')

  - if flash[:notice]
    .notice
      = flash[:notice]
  

  - if flash[:alert]
    .alert
      = flash[:alert]

  .content
    == yield

app/views/layouts/devise.html.slim
doctype html
html

head
   title Cadastre
   =stylesheet_link_tag  'devise', media: 'all', 'data-turbolinks-track' => true
   =javascript_include_tag 'devise', 'data-turbolinks-track' => true
   =csrf_meta_tags

body
  nav class="navbar navbar-inverse navbar-fixed-top"
    .container-fluid
      .navbar-header
        =link_to(image_tag("cadastre.png", height: 50), root_path)
      

      #navbar.navbar-collapse.collapse
        ul class="nav navbar-nav navbar-right"
          li = link_to 'Entrar', new_user_session_path
          li = link_to 'Cadastrar-se', new_user_registration_path
 

  - if flash[:notice]
      .notice
        = flash[:notice]


  - if flash[:alert]
      .alert
        = flash[:alert]


  .content
    ==yield

app/views/pacients/_form.html.slim
- if @pacient.errors.any?
  h4 class="error" Há erros no formulário:

= simple_form_for pacient, html: { class: "form-horizontal" } do |f|
  = f.input :name, input_html: { class: "form-control", placeholder: "Nome completo" }, wrapper_html: { class: "form-group" }

  = f.input :birth, input_html: {class: "form-control", placeholder: "dd/mm/aaaa"}, wrapper_html: {class: "form-group"}

  = f.input :dependents, input_html: {class: "form-control", placeholder: "0"}, wrapper_html: {class: "form-group"}

  = f.input :cpf, input_html: {class: "form-control", placeholder: "xxx.xxx.xxx-xx"}, wrapper_html: {class: "form-group"}

  = f.input :picture, wrapper_html: {class: "form-group"}

  = f.submit "Cadastrar", class: "btn btn-default"

app/views/pacients/edit.html.slim
h1 Editar Paciente

= render :partial => 'form', :locals => {:pacient => @pacient}

app/views/pacients/index.html.slim
table class="table table-bordered" style="margin: 20px auto; max-width: 960;"
  tr
    th = t '.name'
    th = t '.dependents'
    th = t '.birth'
    th = t '.cpf'
    th = t '.owner'

  - @pacients.each do |pacient|
    tr
      - if pacient.user_id == current_user.id
        td = link_to(pacient.name, pacient_path(pacient.id))
      - else
        td = pacient.name
      td = pacient.dependents
      td = pacient.birth
      td = pacient.cpf
      - if user_signed_in?
        - if pacient.user_id == current_user.id
          td 
            = link_to("", edit_pacient_path(pacient.id), class: "glyphicon glyphicon-edit", "data-toggle" => "tooltip", title: "Editar")
            = link_to("", pacient_path(pacient.id), method: :delete, class: "glyphicon glyphicon-remove", "data-toggle" => "tooltip", title: "Apagar")
        - else
          td = pacient.user.email

app/views/pacients/new.html.slim
h1 = t '.cadastre'

= render :partial => 'form', :locals => {:pacient => @pacient}

app/views/pacients/show.html.slim
= image_tag(@pacient.picture_url) if @pacient.picture?
h1 = @pacient.name